spring.datasource:
  url: jdbc:postgresql://localhost:5432/faildb
  username: user
  password: pwd

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: create